# Generated by Django 5.2.6 on 2025-10-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abo",
                    models.CharField(
                        choices=[("O", "O"), ("A", "A"), ("B", "B"), ("AB", "AB")],
                        max_length=2,
                    ),
                ),
                (
                    "rh",
                    models.CharField(
                        choices=[("+", "Rh+"), ("-", "Rh-")], max_length=1
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("last_donation", models.DateField(blank=True, null=True)),
                ("eligibility_consent", models.BooleanField(default=False)),
                ("public_alias", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["city"], name="give_pulse__city_91c545_idx"),
                    models.Index(
                        fields=["is_verified"], name="give_pulse__is_veri_0490b5_idx"
                    ),
                ],
                "unique_together": {("name", "city")},
            },
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units_requested", models.PositiveIntegerField()),
                ("units_fulfilled", models.PositiveIntegerField(default=0)),
                (
                    "abo",
                    models.CharField(
                        choices=[("O", "O"), ("A", "A"), ("B", "B"), ("AB", "AB")],
                        max_length=2,
                    ),
                ),
                (
                    "rh",
                    models.CharField(
                        choices=[("+", "Rh+"), ("-", "Rh-")], max_length=1
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("deadline_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partial", "Partial"),
                            ("fulfilled", "Fulfilled"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_requests",
                        to="give_pulse_app.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("checked_in", "Checked-in"),
                            ("donated", "Donated"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("donated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="give_pulse_app.bloodrequest",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="give_pulse_app.donor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="give_pulse_app.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="staff", max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="give_pulse_app.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.PositiveIntegerField(default=1)),
                (
                    "certificate_file",
                    models.FileField(blank=True, upload_to="certificates/"),
                ),
                ("certificate_serial", models.CharField(blank=True, max_length=40)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation",
                        to="give_pulse_app.match",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="give_pulse_app.staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_blood_requests",
                to="give_pulse_app.staff",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("donor", "Donor"),
                            ("staff", "Staff"),
                            ("admin", "Admin"),
                        ],
                        default="guest",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="give_pulse__email_186e7a_idx"),
                    models.Index(fields=["role"], name="give_pulse__role_e5ea79_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="give_pulse_app.user",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor",
                to="give_pulse_app.user",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="give_pulse__status_24a40d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("blood_request", "donor")},
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["confirmed_at"], name="give_pulse__confirm_b691ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(fields=["status"], name="give_pulse__status_5adfda_idx"),
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(
                fields=["deadline_at"], name="give_pulse__deadlin_17cfca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(fields=["city"], name="give_pulse__city_5bc0f9_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["hospital", "is_verified"],
                name="give_pulse__hospita_8357ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["city"], name="give_pulse__city_d1ed41_idx"),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["abo", "rh"], name="give_pulse__abo_2ec2db_idx"),
        ),
    ]
