# Generated by Django 5.2.6 on 2025-10-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["city__name", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="bloodrequest",
            new_name="give_pulse__city_id_1fb622_idx",
            old_name="give_pulse__city_5bc0f9_idx",
        ),
        migrations.RenameIndex(
            model_name="donor",
            new_name="give_pulse__city_id_49c70c_idx",
            old_name="give_pulse__city_d1ed41_idx",
        ),
        migrations.RenameIndex(
            model_name="hospital",
            new_name="give_pulse__city_id_f07e9f_idx",
            old_name="give_pulse__city_91c545_idx",
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blood_requests",
                to="give_pulse_app.city",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donors",
                to="give_pulse_app.city",
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hospitals",
                to="give_pulse_app.city",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="give_pulse_app.city",
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blood_requests",
                to="give_pulse_app.district",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donors",
                to="give_pulse_app.district",
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hospitals",
                to="give_pulse_app.district",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("city", "name")},
        ),
    ]
