# Generated by Django 5.2.6 on 2025-10-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0002_city_district_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="district",
            name="city",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="district",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="district",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="district",
        ),
        migrations.AddField(
            model_name="city",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="give_pulse_app.governorate",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["governorate"], name="give_pulse__governo_582284_idx"
            ),
        ),
        migrations.DeleteModel(
            name="District",
        ),
    ]
