# Generated by Django 5.2.6 on 2025-10-02 09:19

import django.core.validators
import give_pulse_app.uploads
import give_pulse_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0003_governorate_alter_district_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="JPEG/PNG/WEBP, ≤2MB, min 128x128",
                upload_to=give_pulse_app.uploads.donor_avatar_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    give_pulse_app.validators.validate_profile_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[give_pulse_app.validators.validate_person_name],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[give_pulse_app.validators.validate_person_name],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[give_pulse_app.validators.validate_phone],
            ),
        ),
    ]
