# Generated by Django 5.2.5 on 2025-10-07 12:41

import django.core.validators
import give_pulse_app.uploads
import give_pulse_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0004_donor_profile_picture_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="cooldown_until",
            field=models.DateTimeField(
                blank=True, help_text="Donor cannot match until this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="JPEG/PNG/WEBP, ≤2MB",
                null=True,
                upload_to=give_pulse_app.uploads.donor_avatar_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    give_pulse_app.validators.validate_profile_image,
                ],
            ),
        ),
    ]
