# Generated by Django 5.2.5 on 2025-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0005_donor_cooldown_until_alter_donor_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationappointment",
            name="qr_code_data",
            field=models.TextField(
                blank=True, help_text="QR code data for verification"
            ),
        ),
        migrations.AddField(
            model_name="donationappointment",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="certificate_serial",
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
