# Generated by Django 5.2.5 on 2025-10-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("give_pulse_app", "0006_donationappointment_qr_code_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Story title (e.g., 'Ahmed's Story')", max_length=200
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        help_text="Name of the person in the story", max_length=100
                    ),
                ),
                ("story_text", models.TextField(help_text="The success story content")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL for the story image (optional)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Whether this story should be displayed"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for displaying stories (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Success Story",
                "verbose_name_plural": "Success Stories",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
